### ISSUE TITLE
The padding around the box looks odd

### ISSUE THREAD

**Issue by neilpat05** [ravindUwU/firefox-refined-findbar#3]
v131.0.3

I'm not a dev, but just tried including this in my userChrome.css file. I am also having Firefox-UI-Fix, so unsure if there is some kind of clash. 

<img width="2032" alt="image" src="https://github.com/user-attachments/assets/705234cb-a2dc-4b63-ad71-d6b3cb5c675a">

**Comment by ravindUwU** [comment]
Hi! 😊
I notice your close button has been moved to the the left of the other controls.

Refined findbar adds a [`padding-inline-start`](https://github.com/ravindUwU/firefox-refined-findbar/blob/d9f158d30bd67c54015b3ce477a700844ad5089c/src/refined-findbar.scss#L82) to the findbar, but not a `padding-inline–end`, because the close button has it's own margin that spaces it out. The fix would probably be to remove the individual margins from immediate children of the findbar and space them out using `gap`, [like how the controls are spaced out already](https://github.com/ravindUwU/firefox-refined-findbar/blob/d9f158d30bd67c54015b3ce477a700844ad5089c/src/refined-findbar.scss#L123-L132). I'm unable to work on & test this immediately, but will over the next couple weeks.

**For an interim fix**, you should be able to add a `padding-inline-end: math.div($space-unit, 3);` after the `-start` rule and copy it over again 🤔. [Here's][play] a playground link; let me know if it works? Thanks!

[play]: https://sass-lang.com/playground/#eJy9Wf9v27gV/9n+K7jWV9udJdfXw7Cq6JBcki3B0kvRGLsbikOPlmiLiCzqSCq2r8v/vvf4RZZkO3WKYUWSSuT7Qr4vn/dITSYnpWKkr6hSUcaV7r/t1kaWVKftkQIGuuPxmLynd0wRSs5ub8lv91QOhr8Rti4kU4qLnOiUaiLZnEmWx4YQaDidZYzQPIHfDZnTLJvR+E6NCEcGRlTBYj7nLDEahEyYDPHRvJ6wNV0WwK9ipci/vLQV16kodSXN0OK/k4TNygUJcG10+LYah/8+SJ5rhSsaBAEdHqNiu9r9CkZkNiJxU42TP3IPM/8QD4fD7sm8zGONpjICejldMhWG4ZB86XZ6oD8ifbR152QuJOlxMpdiSdBJYcbyhU4dyxAsJ0W5SMkEOTsnfE6Qnbx7BwLMkBdntffJn62YvJIxAvlDGO4PQWOn8wCGyMDnT+MdEZw1qreSuvADW5BMlzI3k2+7MNIL4pTFdzOxDhTLWKyFBCWDbufs8uLsnz/e/PL58uofl9fwO/18en0dkWee/hPNRc6Td/2UL9IMfnX/12ejGuP70+nZ5eez09uLfVxznidBTBUDvbnimt+zvfznV6dnH6+mV2e3B6VAdsRpkHAaS5ATq5acny9vri8+/3zz8fywCJZrLlmwgkg33BA+3ZMlX0M6jF8SxReR0lRq8nLc7UAu8ZwlATLOwBlg3d48E1RHRMuSjar3gIJZ8iXIjshMaC2WtbkEnEchISMy+WuxHnVxZlYCUa5qctxIsIDAKljiZ3DKJKVxVaczvfhl+hn2ijwHPNec2vpm3/jW5s3ZmiXNxPXpjxfX9vH84hZYPkyvbn7C92EXf5zpGMDMyzEG8YkJ1ILGjJQyG/RTrYtoPF6tVuFS/MGzjIZCLsZ3bLOkSjM5XlDN7hgr4BFgSbKQq1Dk2SZcl1kfnFSXmOpl9pPaEbx6bWRO3rx5M14jDfIBIyiZS2QmzpGBimnGAnA5ptur72zWaUlzBYm/jIiZ//fg1dAlVGfy6jDVZFhPu0PKEC8f1zY5SturujanwtD2jG2CMucQhJPvizXuvROLXFOeRwQfID6ReeYCalKsiRIZTzxGAqgtWeAoIVsLKinABIxkQhq9BU0Sni/AdBlkRmBSJSJYtMKE3w9qaxiR1/s4IEIeowcGCKUPAmECYBqSEEfGZAqVym8W5hRWLwq1LqMIJ9mGFI6FJVj2IOvDmRQrxeSZNQCTI9grWbG+BEmSMaKFFU1nYINS14WYwujVYSUCbVyHuBtHEVVsZs2mAJhst27DFYsCqqlDA2LwwYpFKjCIl49SOxJBNSItwEDzdZ5/aUPMw37CKlQCAeLQ5XtYSQx/mTSLdnEQSJrwEqDIBoEWAmqutHAUNEiGO4XK7jPY7g6QNmjvcESW4p6BAUlZkNnGhJ0W5NmSyQV7huOm2CM7dDKaiLkTjSM2Jo2RtCgiEkwwsLcm++EH9767faDft13rkSBjc/3ErbckmBV8owhYW7DiiU4j8or8iS8LIcGT2qa2TYLTnEOeNLLgFiEAQ3+VspyoVKzyEUFgMe8pTxKWh0hLPS+IDye7uGcM8uKT5XjXx1LT/9W69HFWUFat8Tu7F6iPiBhSZFbALrpMU8i389uUJmK13eGY/N1lmGNX0ObcM59vFDaEaez1x9s8XqU8TgnHBneesTUBmAI3h+Qjw0CzslOIgj+QJQO0kRAPCuKKJFD6Y00SpiAwEooNKXbGtqpAuC2NNdk9g8JDSoVBvKAFRt/uOuxuYRrScQtjNtRekL+Rl5agY9W3ELPt9DaZgckdoodaeEzZWgO6rF10NJocXKeGeez1VpIWUFS9e23p/A/PC1ePALyAEgv3jj/tXiy4ufbEmKvdqzg5aHbrAmIlEQx8DtgnwI4mvTFjCEsWiL7E5L8Z134vFRDAmea+EvqC5IbAaoWTy7wB0FzlfUCNgiH4Q+T8XvL4zswC8CQWO8AlUS70IFxyjO9s6NdcT8hmQu+66HEA2EP/0K3+GreZ2gY746JUrV2F5NIk4+7mHtmZ832ngTpHetXUdA9bDq+2dR62Cucu9C/27pb0+RdzavLY1pofET+xsGIenBxrMgd2CAp1M3Wdi6fO53ssQ1IKEYVwDRM2gnxGQ7mA06vtAEZYWhI2p2WmQy/WhaPJ7EbEedlVwPkQDHeTse3apyXFiyiDBjcQ80BvCrYv7BqV6OtR9zXyh3q8N5TvBP0RSm2MHyhV7RDfotOZO3tBG2xj1B/G7BIa1jsuXl0fGZHXEEJ/cUX/21qY/0/wd60XUghA6Q3/VLmB4a6km7d2gj14TdRkwjersuyVLvt6SNkn40+WNHuHyrBNVZhbTkkhAX3lptLi3oOGksNr9yvFtu6grLYP2k54mviWCxqjbet48+w444kqW65oDu9R2giDuYhLFdxzxfEezS0A2hoLZTbkLY0bdDHvaQAt5orpvaSAiDA1bMRCWF0rmQevEc4mRUY3ER4JWIPB4LLSm6zqE6Dhi+9yphRD8LddA3Rrcy4Vgj5iGIm3iALnOIDsDcHGhkov0+OuFguGNwhho7hERlgFw4jYTWAuFCsTEcQwiMuIKTYVMwZdIMjECwl4iSm8ealmCXORZWJlKsj5zXt7fToy0mvrXZqiZcrYjEGJl8xBHLnnlPTcnasTe5UrzWgCXU6CV1XzjWsH9psCBcA8xyZaYjkUOaIkuWMbPCN7oV6Hee9VDpttwKEJW0dk4Hx6wii01uaWERuOJTS/KGqw7/KwKif7BCInhMpgd25kbzPN86DnLGY0Dv3/jXDpWc95OVb04oBoc7MAPd5gu/IdqiHe+DodPRMDT5FN18fI3ukRdtsCLM/Pv1QK9xgYzNFY3vDhmLb1qF51B6+OWk3TEweW0+xPjulhWjRm0nccHsNr3Zw9rc2YXmEyQZegWFwatPU29j21Y917Agtqh7aDbU39ruN/YCX8hIM7wFuS1lpJnAmFUCiISUFhIeyxDUzgiLn/Ju374dGN2jkchSUvmvcMcBRhhC0LvTFHZT8Pe8RLJFxVbbg6GWd0xrLIspkd75QAr/TGoP7TDq7uVmEPdvgr8SEJyKRSU0My8In3D4LaPrdZHc+/VIQPzmmH1Vqo8jq3RjVmaBrlazuwt+vN9R+08NeE1e7naxLh5wE/IpLpzflNRPBWlOclM5UthKhMqkpjKhrWkBOex1kJkSBL/IKo4FQWQ42GTiTsbud2PpG0vpA88oHk4PeRnc8jh7+O1D+O1L+NHP40cuDLyKMfRg59F9l+Fml+FRniZ6X/AlE9P+I=?s=L83C3-L83C48

**Comment by neilpat05** [comment]
It still looks the same to me, actually. I do want to highlight that I'm not a developer and solely copied that code. Either way, thank you for your help, mate.

> I'm unable to work on & test this immediately, but will over the next couple weeks. 

I'm glad you responded and tried helping me with an interim fix.

**Comment by neilpat05** [comment]
Thank you for the support @ravindUwU. 

This solved my issue. I just wanted to let you know that the close button is on the left of other controls, even after the update. I'm unsure if that was the intended goal.
I'm also using Firefox-UI-Fix. 

<img width="2032" alt="image" src="https://github.com/user-attachments/assets/08ffc34b-7aac-416d-bbe7-b713538c00af">

**Comment by ravindUwU** [comment]
Yup! The close button on the left the other controls is probably part of Firefox-UI-Fix 🤔, whereas the fix for this issue simply "resets" the horizontal spacing in between & on either side of those controls, and they seem to work together just fine.

Thanks for confirming! 😄
